version: '3.8'

services:
  myapi:
    build:
      context: .
    ports:
      - 3000:3000
    command: node app.js
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.entrypoints=http
