version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - 3000:3000
    command: node app.js
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.rule=Host(`test.hamood.dev`)
      - traefik.http.services.api.loadbalancer.server.port=3000
      - traefik.http.routers.api.tls.certresolver=staging
      - traefik.docker.network=traefik_default
